version: '3.3'
services:

  #api service
  api:
    image: bookapi
    build: .
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - api-net

  #mongodb service
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - api-net

volumes:
  mongodata:

networks:
  api-net:
    driver: bridge